name: Build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.container-runtime }}
    strategy:
      fail-fast: false
      matrix:
#        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        container-runtime: [docker, podman]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - name: Remove docker if needed
        if: matrix.container-runtime == 'podman'
        run: |
          dpkg -l | grep -i docker
          sudo apt-get purge docker-ce docker-ce-cli

      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'

      - name: Build with Maven
        run: |
          mkdir -p ~/.redhat
          echo '{"disabled":true}' >> ~/.redhat/io.quarkus.analytics.localconfig
          ./mvnw install -B -ntp

      - name: Fail if there are uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain | grep -v antora.yml) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }
